- name: "Install operating system packages"
  apt:
    name:
      - curl
      - git
      - xterm
      - unzip
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: Add an Apt subscription key - Docker
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: true

- name: "Install operating system packages"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 21805A48E6CBBA6B991ABE76646193862B759810

- name: Add ppa - Kathara
  apt_repository:
    repo: ppa:katharaframework/kathara
    state: present

- name: "Add kathara"
  apt:
    name: "kathara"
    state: latest
    update_cache: yes

- name: Add the user with a bash shell, adding the group 'docker'
  user:
    name: "{{user_name}}"
    shell: /bin/bash
    groups: docker
    append: yes
